name: Daily Cricket Bot

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5:00 AM UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "📰 Daily cricket post: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
